# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7d0371667e249d5aeacfde06be3855b483fd09f5bb6a4301c0a015b9b7ec4c2e9cc9422be03e4811ac81b49b40ed17f38950422db3e92289ce2f3e33762da9

test:
  secret_key_base: 95a504683031a9ce9678545018606dc0e0b5f12dede3b4092922ea220089085fbb92bfdade4b5a3f47025adc0086c50ac017cf242063f3864b8a9a32267c1773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
